### ISSUE TITLE
添加班级那里出问题了

### ISSUE THREAD

**Issue by 2002111hhj** [cckevincyh/StudentSystem#7]
下拉无法显示，是数据库出问题了吗？

**Comment by 2002111hhj** [comment]
谢谢

**Comment by 2002111hhj** [comment]
顺便问一下数据库需要修改哪里吗，谢谢大佬

**Comment by cckevincyh** [comment]
> 下拉无法显示，是数据库出问题了吗？

需要执行StudentSystemDao.sql里面的脚本，看看控制台有没有报错，再看看插入的数据中文有没有问题，可能是字符集没设置对

**Comment by swater1234** [comment]
添加学生的时候总是失败，Cannot add or update a child row: a foreign key constraint fails (`studentsystemdao`.`tb_student`, CONSTRAINT `tb_student_ibfk_3` FOREIGN KEY (`Department_Name`) REFERENCES `tb_department` (`Department_Name`))
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
